
AZURE_OPENAI_API_KEY = "AIkg5CJq34sgoJaRg6DnO4dViK3e2t8cIPnfQTtxUtWDFcJkYDDqJQQJ99BGACHYHv6XJ3w3AAAAACOGLjBK"
AZURE_OPENAI_ENDPOINT = "https://tradeguard3.cognitiveservices.azure.com"
AZURE_OPENAI_API_VERSION = "2024-08-01-preview"
AZURE_OPENAI_DEPLOYMENT = "gpt-4o"
TAVILY_API_KEY = "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"